(package "jcs-emacs"
         "8.2.2"
         "Emacs configuration works across all OSs")

(website-url "https://github.com/jcs-emacs/jcs-emacs")
(keywords "lisp" "config")

(script "test" "echo \"Error: no test specified\" && exit 1")

(depends-on "emacs" "29.1")

(files "early-init.el" "init.el"
       "lisp/*.el"
       "lisp/lib/*.el"
       "site-lisp/*.el"
	   "modules/**"
       "banners/**"
       "fonts/**"
       "templates/**")
