;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        end-of-buffer
        helm-M-x
        jcs-mc/mark-next-like-this
        jcs-mc/mark-previous-like-this
        jcs-next-blank-line
        jcs-other-window-next
        jcs-other-window-prev
        jcs-previous-blank-line
        jcs-smart-indent-down
        jcs-smart-indent-up
        jcs-toggle-sublimity-mode
        move-text-up
        reload-emacs
        ))
