;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        jcs-electric-backspace
        jcs-forward-delete-word
        jcs-forward-kill-word-capital
        jcs-py-indent-down
        jcs-py-indent-up
        jcs-smart-indent-down
        jcs-smart-indent-up
        jcs-web-backward-delete-word
        jcs-web-backward-delete-word-capital
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        end-of-buffer
        helm-M-x
        jcs-end-of-line
        jcs-mc/mark-next-like-this
        jcs-mc/mark-previous-like-this
        jcs-next-blank-line
        jcs-other-window-next
        jcs-other-window-prev
        jcs-previous-blank-line
        jcs-toggle-sublimity-mode
        jcs-untabify-save-buffer
        move-text-up
        reload-emacs
        ))
